version: "3.5"
services:
    zabbix-server-pgsql:
        image: zabbix/zabbix-server-pgsql:alpine-5.0-latest
        restart: unless-stopped
        depends_on: 
            - postgres-server
        environment: 
            - DB_SERVER_HOST=postgres-server
            - DB_SERVER_PORT=5432
            - POSTGRES_USER=zabbix
            - POSTGRES_PASSWORD=zabbix_pwd
            - POSTGRES_DB=zabbix
        ports:
            - "10051:10051"
        networks:
            - zabbix

    zabbix-web-nginx-pgsql:
        image: zabbix/zabbix-web-nginx-pgsql:alpine-5.0-latest
        depends_on: 
            - zabbix-server-pgsql
        environment: 
            - DB_SERVER_HOST=postgres-server
            - POSTGRES_USER=zabbix
            - POSTGRES_PASSWORD=zabbix_pwd
            - ZBX_SERVER_HOST=zabbix-server-pgsql
            - PHP_TZ=Asia/Tehran
        ports:
            - "80:8080"
        networks:
            - zabbix
    
    agent:
        image: zabbix/zabbix-agent2:latest
        privileged: true
        depends_on: 
            - zabbix-server-pgsql
        environment: 
            - ZBX_HOSTNAME=Zabbix server
            - ZBX_SERVER_HOST=zabbix-server-pgsql
        ports:
            - "10050:10050"
        networks:
            - zabbix
    postgres-server:
        image: postgres:latest
        #        volumes:
                #            - "./pgsql_data:/var/lib/postgresql/data/pgdata"
        environment: 
            - POSTGRES_USER=zabbix
            - POSTGRES_PASSWORD=zabbix_pwd
            - POSTGRES_DB=zabbix
              #            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        networks:
            - zabbix
networks:
    zabbix:
